services:
  db:
    container_name: ap-education_postgres
    image: postgres:18.0-trixie
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ap-education_postgres:/var/lib/postgresql
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready']

  pgadmin:
    container_name: ap-education_pgadmin
    image: dpage/pgadmin4:9.10
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - 5050:80

  studio:
    container_name: ap-education_studio
    build:
      context: ./
      dockerfile: ./Dockerfile.prisma-studio
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 51212:51212
    volumes:
      - type: bind
        source: ./.env
        target: /usr/src/app/.env

  redis:
    container_name: ap-education_redis
    image: redis:8.6.1
    ports:
      - 6379:6379

  api:
    container_name: ap-education_api
    build:
      context: ./
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./.env
        target: /usr/src/app/.env
      - type: bind
        source: ./index.ts
        target: /usr/src/app/index.ts
      - type: bind
        source: ./src
        target: /usr/src/app/src
      - type: bind
        source: ./prisma
        target: /usr/src/app/prisma
      # - type: bind
      #   source: ./generated
      #   target: /usr/src/app/generated

volumes:
  ap-education_postgres:
